version: 2

sources:
  - name: raw
    database: |
      {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME') }}
    schema: |
      {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA') }}
    tables:
      - name: raw__nsw_doe_datansw__master_dataset
        loader: Dagster
        loaded_at_field: _load_timestamp
        columns:
          - name: School_Code
            # doesnt make its way into dagster :(
            # data_tests:
            #   - dbt_expectations.expect_column_values_to_not_be_null:
            #       row_condition: "School_Code is not null" # (Optional)
        meta:
          dagster:
            asset_key: ["{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA') }}","raw__nsw_doe_datansw__master_dataset"] # This metadata specifies the corresponding Dagster asset for this dbt source.

        quoting:
          database: true
          schema: false
          identifier: false

        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}

      - name: raw__nsw_doe_datansw__ram
        meta:
          dagster:
            asset_key: ["{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA') }}","raw__nsw_doe_datansw__ram"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_aparent_retention_rate_10_to_12
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__aparent_retention_rate_10_to_12"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_aparent_retention_rate_7_to_10
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__aparent_retention_rate_7_to_10"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_aparent_retention_rate_aboriginal_and_or_torres_strait_islanders
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__aparent_retention_rate_aboriginal_and_or_torres_strait_islanders"] # This metadata specifies the corresponding Dagster asset for this dbt source.

      - name: raw_nsw_doe_datansw_class_size
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__class_size"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_early_childhood_education_centres
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__early_childhood_education_centres"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_enrolments_central
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__enrolments_central"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_enrolments_primary
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__enrolments_primary"] # This metadata specifies the corresponding Dagster asset for this dbt source.

      - name: raw_nsw_doe_datansw_enrolments_secondary
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__enrolments_secondary"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_enrolments_ssp
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__enrolments_ssp"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_incidents_2020_part_1
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__incidents_2020_part_1"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_incidents_2020_part_2
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__incidents_2020_part_2"] # This metadata specifies the corresponding Dagster asset for this dbt source.

      - name: raw_nsw_doe_datansw_incidents_2021_part_1
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__incidents_2021_part_1"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_incidents_2021_part_2
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__incidents_2021_part_2"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_incidents_2022_part_1
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__incidents_2022_part_1"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_nsw_doe_datansw_incidents_2022_part_2
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__incidents_2022_part_2"] # This metadata specifies the corresponding Dagster asset for this dbt source.

      - name: raw_nsw_doe_datansw_university
        meta:
          dagster:
            asset_key: ["raw__nsw_doe_datansw__university"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw__nsw_doe_datansw__apprenticeship_traineeship_training_contract_approvals
        meta:
          dagster:
            asset_key: ["{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA') }}","raw__nsw_doe_datansw__apprenticeship_traineeship_training_contract_approvals"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw__nsw_doe_datansw__apprenticeship_traineeship_training_contract_completions
        meta:
          dagster:
            asset_key: ["{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA') }}","raw__nsw_doe_datansw__apprenticeship_traineeship_training_contract_completions"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw__nsw_doe_datansw__apprenticeship_traineeship_training_contract_in_training
        meta:
          dagster:
            asset_key: ["{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA') }}","raw__nsw_doe_datansw__apprenticeship_traineeship_training_contract_in_training"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw__nsw_doe_datansw__attendance
        meta:
          dagster:
            asset_key: ["{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA') }}","raw__nsw_doe_datansw__attendance"] # This metadata specifies the corresponding Dagster asset for this dbt source.
