version: 2

sources:
  - name: raw
    database: |
      {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME') }}
    schema: raw
    tables:
      - name: raw__acara__staff_numbers
        # meta:
        #   dagster:
        #     asset_key: ["raw","raw_customers_py"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw__acara__student_numbers
