version: 2

sources:
  - name: raw_github
    database: |
      {%- if  target.name == "dev" -%} {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME__DEV') }}
      {%- elif target.name == "prod"  -%} {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME__PROD') }}
      {%- else -%} invalid_database
      {%- endif -%}
    schema: raw_github
    tables:
      - name: issues
        # meta:
        #   dagster:
        #     asset_key: ["raw","raw_customers_py"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: issues__comments__reactions
      - name: issues__reactions