version: 2

sources:
  - name: raw
    database: |
      {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME') }}
    schema: raw
    tables:
      - name: raw_github_reactions_issues
        meta:
          dagster:
            asset_key: ["raw_github_reactions_issues"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_github_reactions_issues__reactions
        meta:
          dagster:
            asset_key: ["raw_github_reactions_issues"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_github_reactions_issues__comments__reactions
        meta:
          dagster:
            asset_key: ["raw_github_reactions_issues"] # This metadata specifies the corresponding Dagster asset for this dbt source.

      # - name: raw_github_reactions_pull_requests
      # - name: raw_github_reactions_pull_requests_reactions
