demo_jaffle_shop_profile:
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DEMO_JAFFLE_SHOP_DB_PATH_AND_DB__DEV') }}"
      database: "{{ env_var('DEMO_JAFFLE_SHOP_DB_NAME__DEV') }}"
      schema: "{{ env_var('DEMO_JAFFLE_SHOP_TARGET_SCHEMA__DEV') }}"
      threads: 4
    prod:
      type: duckdb
      path: "md:{{ env_var('DEMO_JAFFLE_SHOP_DB_NAME__PROD') }}"
      schema: "{{ env_var('DEMO_JAFFLE_SHOP_TARGET_SCHEMA__PROD') }}"
      threads: 4
  target: "{{ env_var('DEMO_JAFFLE_SHOP__ENV') }}"