nsw_doe_data_stack_in_a_box_profile:
  outputs:
    dev:
      type: duckdb
      path: "../../{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_PATH__DEV') }}"
      database: "{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME__DEV') }}"
      schema: jaffle_shop
      threads: 4
    prod:
      type: duckdb
      path: "md:{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME__PROD') }}"
      schema: jaffle_shop
      threads: 4
  target: "{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX__ENV') }}"