version: 2

sources:
  - name: raw
    database: |
      {%- if  target.name == "dev" -%} {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME__DEV') }}
      {%- elif target.name == "prod"  -%} {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME__PROD') }}
      {%- else -%} invalid_database
      {%- endif -%}
    schema: raw  
    tables:
      - name: raw_payments_py
        meta:
          dagster:
            asset_key: ["raw_payments_py"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_orders_py
        meta:
          dagster:
            asset_key: ["raw_orders_py"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_customers_py
        meta:
          dagster:
            asset_key: ["raw_customers_py"] # This metadata specifies the corresponding Dagster asset for this dbt source.
