name: 'nsw_doe_data_stack_in_a_box'

config-version: 2
version: '0.1'

profile: 'nsw_doe_data_stack_in_a_box_profile'
# profile: 'my_dbt_trino_project'

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"
  "dbt_date:time_zone": "America/Los_Angeles"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["data_tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

tests:
  +store_failures: true  # all tests

models:
  +tags:
    - "all"
  nsw_doe_data_stack_in_a_box:
    +materialized: table
    # +schema: common
    dimensional:
      materialized: table
      dimensions_shared:
        # +pre_hook: ["select 4;"] # was going to apply missing_member_column as a hook to all dimensions, but for now defining in model config
    staging:
      materialized: view
      github:
        +tags:
          - "api" # tagging api so i know which models require API keys
      google_analytics:
        +tags:
          - "api" # tagging api so i know which models require API keys
