version: 2

sources:
  - name: raw
    database: |
      {%- if  target.name == "dev" -%} {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME__DEV') }}
      {%- elif target.name == "prod"  -%} {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME__PROD') }}
      {%- else -%} invalid_database
      {%- endif -%}
    schema: raw
    tables:
      - name: raw_google_analytics_metrics
        meta:
          dagster:
            asset_key: ["raw_google_analytics_metrics"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_google_analytics_dimensions
        meta:
          dagster:
            asset_key: ["raw_google_analytics_dimensions"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_google_analytics_sample_analytics_data1
        meta:
          dagster:
            asset_key: ["raw_google_analytics_sample_analytics_data1"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_google_analytics_sample_analytics_data2
        meta:
          dagster:
            asset_key: ["raw_google_analytics_sample_analytics_data2"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_google_analytics_user_metrics_date
        meta:
          dagster:
            asset_key: ["raw_google_analytics_user_metrics_date"] # This metadata specifies the corresponding Dagster asset for this dbt source.
