version: 2

sources:
  - name: raw
    database: |
      {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME') }}
    schema: |
      {{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA') }}
    tables:
      - name: raw__nsw_doe_datahub__master_dataset
        loader: Dagster
        loaded_at_field: _load_timestamp
        meta:
          dagster:
            asset_key: ["{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA') }}","raw__nsw_doe_datahub__master_dataset"] # This metadata specifies the corresponding Dagster asset for this dbt source.

        quoting:
          database: true
          schema: false
          identifier: false

        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}

      - name: raw__nsw_doe_datahub__ram
        meta:
          dagster:
            asset_key: ["{{ env_var('NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA') }}","raw__nsw_doe_datahub__ram"] # This metadata specifies the corresponding Dagster asset for this dbt source.
