on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  ci:
    env:
      NSW_DOE_DATA_STACK_IN_A_BOX__ENV: dev
      NSW_DOE_DATA_STACK_IN_A_BOX_DBT_PROJECT_DIR: ${GITHUB_WORKSPACE}/nsw-doe-data-stack-in-a-box/transformation/transformation_nsw_doe

      NSW_DOE_DATA_STACK_IN_A_BOX_DB_PATH__DEV: ${GITHUB_WORKSPACE}/nsw-doe-data-stack-in-a-box/reports/sources/nsw_doe_data_stack_in_a_box__dev
      NSW_DOE_DATA_STACK_IN_A_BOX_DB_PATH_AND_DB__DEV: ${GITHUB_WORKSPACE}/nsw-doe-data-stack-in-a-box/reports/sources/nsw_doe_data_stack_in_a_box__dev/nsw_doe_data_stack_in_a_box__dev.duckdb
      NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME__DEV: nsw_doe_data_stack_in_a_box__dev
      NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA__DEV: analytics

      NSW_DOE_DATA_STACK_IN_A_BOX_DB_PATH__PROD:  # not needed "/reports/nsw_doe_data_stack_in_a_box__prod.duckdb"
      NSW_DOE_DATA_STACK_IN_A_BOX_DB_NAME__PROD: nsw_doe_data_stack_in_a_box__prod
      NSW_DOE_DATA_STACK_IN_A_BOX_TARGET_SCHEMA__PROD: analytics


      # DEMO_JAFFLE_SHOP__ENV: dev
      # DEMO_JAFFLE_SHOP_DBT_PROJECT_DIR: ${GITHUB_WORKSPACE}/nsw-doe-data-stack-in-a-box/transformation/demo_transformation_jaffle_shop

      # DEMO_JAFFLE_SHOP_DB_PATH__DEV: ${GITHUB_WORKSPACE}/nsw-doe-data-stack-in-a-box/reports/sources/demo_jaffle_shop__dev
      # DEMO_JAFFLE_SHOP_DB_PATH_AND_DB__DEV: ${GITHUB_WORKSPACE}/nsw-doe-data-stack-in-a-box/reports/sources/demo_jaffle_shop__dev/demo_jaffle_shop__dev.duckdb
      # DEMO_JAFFLE_SHOP_DB_NAME__DEV: demo_jaffle_shop__dev
      # DEMO_JAFFLE_SHOP_TARGET_SCHEMA__DEV: analytics

      # DEMO_JAFFLE_SHOP_DB_PATH__PROD:  # not needed "/reports/nsw_doe_data_stack_in_a_box__prod.duckdb"
      # DEMO_JAFFLE_SHOP_DB_NAME__PROD: demo_jaffle_shop__prod
      # DEMO_JAFFLE_SHOP_TARGET_SCHEMA__PROD: demo
    name: CI Check
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.11.x"
      - name: check python with ruff
        uses: chartboost/ruff-action@v1
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
      - name: Install uv
        run: python3 -m pip install uv
      - name: Install Python requirements
        run: uv pip install --system -r requirements.txt
      - name: pytest
        run: cd orchestration && pytest
      - name: Dbt checks
        run: |
          cd transformation/transformation_nsw_doe
          dbt deps
          dbt parse
          mf validate-configs
      - name: Lint SQL
        run: sqlfluff lint --format github-annotation-native
      # - name: Build Evidence
      #   env:
      #     EVIDENCE_DATABASE: "duckdb"
      #     EVIDENCE_DUCKDB_FILENAME: "octocatalog.db"
      #   run: |
      #     npm install --prefix ./reports
      #     npm run sources --prefix ./reports
      #     npm run build --prefix ./reports
